team_dict = {
	'New Orleans Saints': 'NO',
	'St. Louis Rams': 'STL',
	'New England Patriots': 'NE',
	'Tampa Bay Buccaneers': 'TB',
	'Philadelphia Eagles': 'PHI',
	'Pittsburgh Steelers': 'PIT',
	'Atlanta Falcons': 'ATL',
	'Cleveland Browns': 'CLE',
	'Cincinnati Bengals': 'CIN',
	'Oakland Raiders': 'OAK',
	'Buffalo Bills': 'BUF',
	'New York Giants': 'NYG',
	'Detroit Lions': 'DET',
	'Carolina Panthers': 'CAR',
	'San Francisco 49ers': 'SF',
	'Indianapolis Colts': 'IND',
	'Seattle Seahawks': 'SEA',
	'Arizona Cardinals': 'ARI',
	'Houston Texans': 'HOU',
	'Tennessee Titans': 'TEN',
	'Jacksonville Jaguars': 'JAC',
	'Chicago Bears': 'CHI',
	'San Diego Chargers': 'SD',
	'Miami Dolphins': 'MIA',
	'New York Jets': 'NYJ',
	'Baltimore Ravens': 'BAL',
	'Kansas City Chiefs': 'KC',
	'Denver Broncos': 'DEN',
	'Washington Redskins': 'WAS',
	'Green Bay Packers': 'GB',
	'Minnesota Vikings': 'MIN',
	'Dallas Cowboys': 'DAL',
}