rbs_2015 = [
    ('A.Abdullah', 'DET'),
    ('J.Ajayi', 'MIA'),
    ('J.Allen', 'BAL'),
    ('C.Anderson', 'DEN'),
    ('A.Andrews', 'TEN'),
    ('C.Artis-Payne', 'CAR'),
    ('M.Asiata', 'MIN'),
    ('J.Banyard', 'JAC'),
    ('K.Barner', 'PHI'),
    ('J.Bell', 'DET'),
    ('L.Bell', 'PIT'),
    ('G.Bernard', 'CIN'),
    ('L.Blount', 'NE'),
    ('A.Blue', 'HOU'),
    ('B.Bolden', 'NE'),
    ('A.Bradshaw', 'IND'),
    ('B.Brown', 'SEA'),
    ('D.Brown', 'SD'),
    ('M.Brown', 'STL'),
    ('R.Burkhead', 'CIN'),
    ('R.Bush', 'SF'),
    ('T.Cadet', 'NO'),
    ('K.Carey', 'CHI'),
    ('J.Charles', 'KC'),
    ('D.Cobb', 'TEN'),
    ('T.Coleman', 'ATL'),
    ('J.Crockett', 'GB'),
    ('I.Crowell', 'CLE'),
    ('B.Cunningham', 'STL'),
    ('O.Darkwa', 'NYG'),
    ('K.Davis', 'KC'),
    ('M.Davis', 'SF'),
    ('B.Dixon', 'BUF'),
    ('S.Draughn', 'SF'),
    ('L.Dunbar', 'DAL'),
    ('A.Ellington', 'ARI'),
    ('J.Forsett', 'BAL'),
    ('M.Forte', 'CHI'),
    ('A.Foster', 'HOU'),
    ('D.Freeman', 'ATL'),
    ('T.Gaffney', 'NE'),
    ('K.Gaskins', 'SF'),
    ('T.Gerhart', 'JAC'),
    ('M.Gillislee', 'BUF'),
    ('M.Gordon', 'SD'),
    ('F.Gore', 'IND'),
    ('C.Grant', 'JAC'),
    ('J.Gray', 'JAC'),
    ('J.Grimes', 'HOU'),
    ('T.Gurley', 'STL'),
    ('D.Harris', 'SF'),
    ('J.Hayne', 'SF'),
    ('R.Helu', 'OAK'),
    ('T.Hightower', 'NO'),
    ('J.Hill', 'CIN'),
    ('R.Hillman', 'DEN'),
    ('A.Hunt', 'HOU'),
    ('K.Hunter', 'NO'),
    ('C.Hyde', 'SF'),
    ('M.Ingram', 'NO'),
    ('C.Ivory', 'NYJ'),
    ('F.Jackson', 'SEA'),
    ('S.Jackson', 'NE'),
    ('M.James', 'TB'),
    ('R.Jennings', 'NYG'),
    ('C.Johnson', 'ARI'),
    ('D.Johnson', 'ARI'),
    ('D.Johnson Jr.', 'CLE'),
    ('M.Jones', 'WAS'),
    ('T.Jones', 'OAK'),
    ('E.Lacy', 'GB'),
    ('J.Langford', 'CHI'),
    ('D.Lewis', 'NE'),
    ('M.Lynch', 'SEA'),
    ('T.Magee', 'BAL'),
    ('D.Martin', 'TB'),
    ('T.Mason', 'STL'),
    ('R.Mathews', 'PHI'),
    ('D.McCluster', 'TEN'),
    ('L.McCoy', 'BUF'),
    ('D.McFadden', 'DAL'),
    ('J.McKinnon', 'MIN'),
    ('C.Michael', 'SEA'),
    ('L.Miller', 'MIA'),
    ('A.Morris', 'WAS'),
    ('R.Mostert', 'CLE'),
    ('M.Murphy', 'NO'),
    ('D.Murray', 'PHI'),
    ('L.Murray', 'OAK'),
    ('J.Olawale', 'OAK'),
    ('B.Oliver', 'SD'),
    ('C.Peerman', 'CIN'),
    ('S.Perry', 'CHI'),
    ('A.Peterson', 'MIN'),
    ('B.Pierce', 'JAC'),
    ('C.Polk', 'HOU'),
    ('B.Powell', 'NYJ'),
    ('B.Rainey', 'TB'),
    ('T.Rawls', 'SEA'),
    ('S.Redd', 'WAS'),
    ('C.Reynolds', 'STL'),
    ('T.Riddick', 'DET'),
    ('S.Ridley', 'NYJ'),
    ('D.Robinson', 'JAC'),
    ('K.Robinson', 'NO'),
    ('J.Rodgers', 'CHI'),
    ('B.Sankey', 'TEN'),
    ('C.Sims', 'TB'),
    ('D.Smith', 'SD'),
    ('R.Smith', 'DAL'),
    ('C.Spiller', 'NO'),
    ('D.Sproles', 'PHI'),
    ('Z.Stacy', 'NYJ'),
    ('J.Starks', 'GB'),
    ('J.Stewart', 'CAR'),
    ('L.Taliaferro', 'BAL'),
    ('S.Taylor', 'ARI'),
    ('P.Thomas', 'WAS'),
    ('C.Thompson', 'WAS'),
    ('J.Thompson', 'DEN'),
    ('J.Todman', 'PIT'),
    ('R.Turbin', 'DAL'),
    ('T.Varga', 'IND'),
    ('S.Vereen', 'NYG'),
    ('T.Ward', 'ATL'),
    ('S.Ware', 'KC'),
    ('T.Watts', 'STL'),
    ('B.Wegher', 'CAR'),
    ('C.West', 'KC'),
    ('T.West', 'BAL'),
    ('J.White', 'NE'),
    ('F.Whittaker', 'CAR'),
    ('A.Williams', 'NYG'),
    ('D.Williams', 'MIA'),
    ('D.Williams', 'PIT'),
    ('K.Williams', 'BUF'),
    ('K.Williams', 'ARI'),
    ('T.Williams', 'IND'),
    ('G.Winn', 'DET'),
    ('G.Winston', 'CLE'),
    ('C.Wood', 'BUF'),
    ('D.Woodhead', 'SD'),
    ('T.Yeldon', 'JAC'),
    ('Z.Zenner', 'DET'),
]

rbs_2012 = [
    ('A.Peterson', ' MIN'),
    ('A.Morris', ' WAS'),
    ('M.Lynch', ' SEA'),
    ('J.Charles', ' KC'),
    ('D.Martin', ' TB'),
    ('A.Foster', ' HOU'),
    ('S.Ridley', ' NE'),
    ('C.Spiller', ' BUF'),
    ('C.Johnson', ' TEN'),
    ('F.Gore', ' SF'),
    ('R.Rice', ' BAL'),
    ('M.Forte', ' CHI'),
    ('B.Green-Ellis', ' CIN'),
    ('S.Greene', ' NYJ'),
    ('S.Jackson', ' STL'),
    ('A.Bradshaw', ' NYG'),
    ('R.Bush', ' MIA'),
    ('T.Richardson', ' CLE'),
    ('L.McCoy', ' PHI'),
    ('V.Ballard', ' IND'),
    ('M.Turner', ' ATL'),
    ('M.Leshoure', ' DET'),
    ('D.Williams', ' CAR'),
    ('W.McGahee', ' DEN'),
    ('D.McFadden', ' OAK'),
    ('R.Mathews', ' SD'),
    ('D.Murray', ' DAL'),
    ('J.Dwyer', ' PIT'),
    ('M.Ingram', ' NO'),
    ('B.Brown', ' PHI'),
    ('B.Pierce', ' BAL'),
    ('K.Moreno', ' DEN'),
    ('D.Richardson', ' STL'),
    ('P.Thomas', ' NO'),
    ('A.Green', ' GB'),
    ('F.Jackson', ' BUF'),
    ('B.Powell', ' NYJ'),
    ('D.Brown', ' IND'),
    ('J.Bell', ' DET'),
    ('M.Jones-Drew', ' JAC'),
    ('M.Bush', ' CHI'),
    ('I.Redman', ' PIT'),
    ('F.Jones', ' DAL'),
    ('A.Brown', ' NYG'),
    ('J.Forsett', ' HOU'),
    ('K.Hunter', ' SF'),
    ('J.Rodgers', ' ATL'),
    ('D.Wilson', ' NYG'),
    ('L.Stephens', ' ARI'),
    ('R.Turbin', ' SEA'),
    ('J.Stewart', ' CAR'),
    ('R.Hillman', ' DEN'),
    ('D.Thomas', ' MIA'),
    ('J.Battle', ' SD'),
    ('P.Hillis', ' KC'),
    ('D.Woodhead', ' NE'),
    ('R.Jennings', ' JAC'),
    ('B.Tate', ' HOU'),
    ('B.Bolden', ' NE'),
    ('M.Hardesty', ' CLE'),
    ('C.Peerman', ' CIN'),
    ('J.Starks', ' GB'),
    ('S.Vereen', ' NE'),
    ('L.Miller', ' MIA'),
    ('C.Benson', ' GB'),
    ('D.Sproles', ' NO'),
    ('B.Wells', ' ARI'),
    ('S.Draughn', ' KC'),
    ('M.Goodson', ' OAK'),
    ('R.Brown', ' SD'),
    ('C.Ivory', ' NO'),
    ('W.Powell', ' ARI'),
    ('M.Owens', ' JAC'),
    ('T.Choice', ' BUF'),
    ('R.Mendenhall', ' PIT'),
    ('J.McKnight', ' NYJ'),
    ('T.Gerhart', ' MIN'),
    ('R.Williams', ' ARI'),
    ('L.Ball', ' DEN'),
    ('D.Harris', ' GB'),
    ('L.Blount', ' TB'),
    ('J.Parmele', ' JAC'),
    ('K.Smith', ' DET'),
    ('R.Grant', ' GB'),
    ('R.Grant', ' WAS'),
    ('L.James', ' SF'),
    ('A.Allen', ' CHI'),
    ('D.Carter', ' IND'),
    ('C.Brinkley', ' SD'),
    ('B.Leonard', ' CIN'),
    ('C.Rainey', ' PIT'),
    ('J.Stewart', ' OAK'),
    ('R.Murphy', ' JAC'),
    ('E.Royster', ' WAS'),
    ('L.Washington', ' SEA'),
    ('J.Hester', ' DEN'),
    ('B.Dixon', ' SF'),
    ('K.Bell', ' CHI'),
    ('K.Bell', ' NYJ'),
    ('L.Dunbar', ' DAL'),
    ('K.Toston', ' JAC'),
    ('D.McCluster', ' KC'),
    ('D.Lewis', ' PHI'),
    ('P.Tanner', ' DAL'),
    ('A.Allen', ' BAL'),
    ('B.Jackson', ' CLE'),
    ('I.Pead', ' STL'),
    ('D.Ware', ' TB'),
    ('B.Batch', ' PIT'),
    ('C.Gray', ' KC'),
    ('K.Lumpkin', ' NYG'),
]

rbs_2013 = [
    ('L.McCoy', ' PHI'),
    ('M.Forte', ' CHI'),
    ('J.Charles', ' KC'),
    ('A.Morris', ' WAS'),
    ('A.Peterson', ' MIN'),
    ('M.Lynch', ' SEA'),
    ('R.Mathews', ' SD'),
    ('E.Lacy', ' GB'),
    ('F.Gore', ' SF'),
    ('D.Murray', ' DAL'),
    ('C.Johnson', ' TEN'),
    ('K.Moreno', ' DEN'),
    ('R.Bush', ' DET'),
    ('Z.Stacy', ' STL'),
    ('C.Spiller', ' BUF'),
    ('F.Jackson', ' BUF'),
    ('L.Bell', ' PIT'),
    ('D.Williams', ' CAR'),
    ('C.Ivory', ' NYJ'),
    ('M.Jones-Drew', ' JAC'),
    ('S.Ridley', ' NE'),
    ('L.Blount', ' NE'),
    ('B.Tate', ' HOU'),
    ('B.Green-Ellis', ' CIN'),
    ('R.Jennings', ' OAK'),
    ('L.Miller', ' MIA'),
    ('B.Powell', ' NYJ'),
    ('G.Bernard', ' CIN'),
    ('R.Mendenhall', ' ARI'),
    ('R.Rice', ' BAL'),
    ('A.Ellington', ' ARI'),
    ('J.Bell', ' DET'),
    ('M.Ball', ' DEN'),
    ('P.Thomas', ' NO'),
    ('S.Jackson', ' ATL'),
    ('A.Foster', ' HOU'),
    ('D.Brown', ' IND'),
    ('B.Rainey', ' CLE'),
    ('B.Rainey', ' TB'),
    ('J.Starks', ' GB'),
    ('A.Brown', ' NYG'),
    ('T.Richardson', ' CLE'),
    ('T.Richardson', ' IND'),
    ('D.Martin', ' TB'),
    ('B.Pierce', ' BAL'),
    ('D.Woodhead', ' SD'),
    ('D.Thomas', ' MIA'),
    ('M.Ingram', ' NO'),
    ('D.McFadden', ' OAK'),
    ('W.McGahee', ' CLE'),
    ('K.Hunter', ' SF'),
    ('J.Rodgers', ' ATL'),
    ('B.Brown', ' PHI'),
    ('S.Greene', ' TEN'),
    ('M.James', ' TB'),
    ('T.Gerhart', ' MIN'),
    ('R.Helu', ' WAS'),
    ('B.Bolden', ' NE'),
    ('R.Turbin', ' SEA'),
    ('B.Cunningham', ' STL'),
    ('J.Todman', ' JAC'),
    ('P.Hillis', ' NYG'),
    ('K.Davis', ' KC'),
    ('C.Ogbonnaya', ' CLE'),
    ('B.Jacobs', ' NYG'),
    ('K.Robinson', ' NO'),
    ('D.Sproles', ' NO'),
    ('R.Hillman', ' DEN'),
    ('D.Richardson', ' STL'),
    ('S.Vereen', ' NE'),
    ('M.Bush', ' CHI'),
    ('J.Dwyer', ' PIT'),
    ('A.Bradshaw', ' IND'),
    ('F.Jones', ' PIT'),
    ('D.Johnson', ' HOU'),
    ('B.Leonard', ' TB'),
    ('J.Stewart', ' CAR'),
    ('E.Baker', ' CLE'),
    ('M.Asiata', ' MIN'),
    ('J.Randle', ' DAL'),
    ('R.Brown', ' SD'),
    ('L.Dunbar', ' DAL'),
    ('D.Wilson', ' NYG'),
    ('A.Smith', ' ATL'),
    ('J.Battle', ' TEN'),
    ('T.Choice', ' BUF'),
    ('T.Choice', ' IND'),
    ('S.Taylor', ' ARI'),
    ('J.Franklin', ' GB'),
    ('T.Richardson', ' CLE'),
    ('T.Richardson', ' IND'),
    ('C.Polk', ' PHI'),
    ('F.Whittaker', ' CLE'),
    ('F.Whittaker', ' SD'),
    ('C.Michael', ' SEA'),
    ('D.Scott', ' NYG'),
    ('J.Grimes', ' HOU'),
    ('D.Robinson', ' JAC'),
    ('V.Ballard', ' IND'),
    ('M.Goodson', ' NYJ'),
    ('L.James', ' SF'),
    ('B.Dixon', ' SF'),
    ('A.Smith', ' ARI'),
    ('D.Karim', ' HOU'),
    ('T.Choice', ' BUF'),
    ('T.Choice', ' IND'),
    ('M.Cox', ' NYG'),
    ('C.Anderson', ' DEN'),
]

rbs_2014 = [
    ('D.Murray', ' DAL'),
    ('L.Bell', ' PIT'),
    ('L.McCoy', ' PHI'),
    ('M.Lynch', ' SEA'),
    ('J.Forsett', ' BAL'),
    ('A.Foster', ' HOU'),
    ('E.Lacy', ' GB'),
    ('J.Hill', ' CIN'),
    ('F.Gore', ' SF'),
    ('L.Miller', ' MIA'),
    ('A.Morris', ' WAS'),
    ('M.Forte', ' CHI'),
    ('J.Charles', ' KC'),
    ('M.Ingram', ' NO'),
    ('J.Bell', ' DET'),
    ('C.Anderson', ' DEN'),
    ('C.Ivory', ' NYJ'),
    ('J.Stewart', ' CAR'),
    ('T.Mason', ' STL'),
    ('A.Williams', ' NYG'),
    ('S.Jackson', ' ATL'),
    ('G.Bernard', ' CIN'),
    ('T.West', ' CLE'),
    ('C.Johnson', ' NYJ'),
    ('A.Ellington', ' ARI'),
    ('R.Jennings', ' NYG'),
    ('I.Crowell', ' CLE'),
    ('B.Oliver', ' SD'),
    ('D.Robinson', ' JAC'),
    ('M.Asiata', ' MIN'),
    ('B.Sankey', ' TEN'),
    ('J.McKinnon', ' MIN'),
    ('D.McFadden', ' OAK'),
    ('A.Blue', ' HOU'),
    ('F.Jackson', ' BUF'),
    ('T.Richardson', ' IND'),
    ('D.Martin', ' TB'),
    ('K.Davis', ' KC'),
    ('R.Hillman', ' DEN'),
    ('B.Dixon', ' BUF'),
    ('A.Bradshaw', ' IND'),
    ('L.Murray', ' OAK'),
    ('J.Gray', ' NE'),
    ('B.Rainey', ' TB'),
    ('S.Greene', ' TEN'),
    ('S.Vereen', ' NE'),
    ('B.Pierce', ' BAL'),
    ('K.Robinson', ' NO'),
    ('D.Herron', ' IND'),
    ('J.Randle', ' DAL'),
    ('S.Ridley', ' NE'),
    ('B.Tate', ' CLE'),
    ('B.Tate', ' MIN'),
    ('B.Tate', ' PIT'),
    ('J.Starks', ' GB'),
    ('C.Hyde', ' SF'),
    ('R.Mathews', ' SD'),
    ('D.Sproles', ' PHI'),
    ('T.Gerhart', ' JAC'),
    ('R.Turbin', ' SEA'),
    ('C.Spiller', ' BUF'),
    ('R.Bush', ' DET'),
    ('Z.Stacy', ' STL'),
    ('L.Taliaferro', ' BAL'),
    ('L.Blount', ' NE'),
    ('L.Blount', ' PIT'),
    ('J.Thompson', ' DEN'),
    ('L.Blount', ' NE'),
    ('L.Blount', ' PIT'),
    ('D.Freeman', ' ATL'),
    ('B.Cunningham', ' STL'),
    ('K.Williams', ' ARI'),
    ('K.Williams', ' SD'),
    ('D.Brown', ' SD'),
    ('P.Thomas', ' NO'),
    ('D.Williams', ' CAR'),
    ('J.Rodgers', ' ATL'),
    ('R.Helu', ' WAS'),
    ('S.Taylor', ' ARI'),
    ('J.Todman', ' JAC'),
    ('C.Sims', ' TB'),
    ('C.Michael', ' SEA'),
    ('M.Ball', ' DEN'),
    ('C.Polk', ' PHI'),
    ('D.Thomas', ' MIA'),
    ('K.Carey', ' CHI'),
    ('J.Grimes', ' HOU'),
    ('K.Moreno', ' MIA'),
    ('F.Whittaker', ' CAR'),
    ('A.Smith', ' ATL'),
    ('B.Powell', ' NYJ'),
    ('D.McCluster', ' TEN'),
    ('B.Brown', ' BUF'),
    ('D.Williams', ' MIA'),
    ('P.Hillis', ' NYG'),
    ('D.Thomas', ' KC'),
    ('L.Dunbar', ' DAL'),
    ('M.Jones-Drew', ' OAK'),
    ('B.Bolden', ' NE'),
    ('J.Banyard', ' MIN'),
    ('S.Johnson', ' JAC'),
    ('D.Reaves', ' CAR'),
    ('A.Peterson', ' MIN'),
    ('S.Redd', ' WAS'),
    ('G.Winn', ' DET'),
    ('D.Harris', ' GB'),
    ('R.Brown', ' SD'),
    ('R.Brown', ' HOU'),
    ('L.Washington', ' TEN'),
    ('T.Riddick', ' DET'),
    ('J.Dwyer', ' ARI'),
    ('C.Ogbonnaya', ' CLE'),
    ('C.Ogbonnaya', ' NYG'),
    ('C.Ogbonnaya', ' CAR'),
    ('C.Peerman', ' CIN'),
    ('M.Grice', ' ARI'),
    ('M.Grice', ' SD'),
    ('D.Archer', ' PIT'),
]
